export const CHANGE_TEXT = 'CHANGE_TEXT';
export const ADD_TODOLIST = 'ADD_TODOLIST';
export const DONE_TODOLIST = 'DONE_TODOLIST';
export const REMOVE_TODOLIST = 'REMOVE_TODOLIST';
export const TIME_START = 'TIME_START';